//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanayeeIdentity_5.Controllers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int FeebBackId { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public string TitLe { get; set; }
    }
}
