//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanayeeIdentity_5.Controllers.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdressDetail> AdressDetails { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<City> Citys { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Schedual> Scheduals { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
    }
}
