//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanayeeIdentity_5.Controllers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumOfWorekerPerCityArea
    {
        public string CityName { get; set; }
        public string AreaName { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> NumOFWorkrs { get; set; }
    }
}
