//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanayeeIdentity_5.Controllers.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PricesInfo> PricesInfoes { get; set; }
        public virtual DbSet<RequstsInfo> RequstsInfoes { get; set; }
        public virtual DbSet<NumOfWorekerPerCityArea> NumOfWorekerPerCityAreas { get; set; }
    
        public virtual ObjectResult<TypeRequstsInMonthOfYear_Result> TypeRequstsInMonthOfYear(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TypeRequstsInMonthOfYear_Result>("TypeRequstsInMonthOfYear", yearParameter);
        }
    
        public virtual ObjectResult<RequstsInMonthOfYear_Result> RequstsInMonthOfYear(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequstsInMonthOfYear_Result>("RequstsInMonthOfYear", yearParameter);
        }
    }
}
