//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanayeeIdentity_5.Controllers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public string Userid { get; set; }
        public int ScedualId { get; set; }
        public System.DateTime RequestDateTime { get; set; }
        public bool Done { get; set; }
        public Nullable<int> AddressId { get; set; }
    
        public virtual AdressDetail AdressDetail { get; set; }
        public virtual Schedual Schedual { get; set; }
    }
}
