//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanayeeIdentity_5.Controllers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Scheduals = new HashSet<Schedual>();
        }
    
        public int WorkerId { get; set; }
        public string UserID { get; set; }
        public string SBIN { get; set; }
        public Nullable<bool> Onwork { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> TotalRate { get; set; }
        public byte[] PhotoBin { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedual> Scheduals { get; set; }
        public virtual Type Type { get; set; }
    }
}
